require "net/http"

namespace :potee do
  desc "Refresh production calendars (config/calendars/*.yml) from xmlcalendar.ru: YEARS=2024-2027"
  task calendars: :environment do
    first, last = ENV.fetch("YEARS", "#{Date.current.year - 1}-#{Date.current.year + 1}").split("-").map(&:to_i)
    WorkCalendar::PRODUCTION.each do |country|
      data = { "holidays" => [], "workdays" => [] }
      (first..(last || first)).each do |year|
        response = Net::HTTP.get_response(URI("https://xmlcalendar.ru/data/#{country.downcase}/#{year}/calendar.json"))
        next puts("#{country} #{year}: #{response.code}, skipped") unless response.is_a?(Net::HTTPSuccess)

        # "days" lists the days off of each month; "N*" is a shortened working
        # day, "N+" a day off moved from a holiday. Absent weekend days are working.
        off = JSON.parse(response.body)["months"].flat_map do |month|
          month["days"].split(",").reject { _1.end_with?("*") }.map { Date.new(year, month["month"], _1.to_i) }
        end
        Date.new(year, 1, 1).upto(Date.new(year, 12, 31)) do |day|
          weekend = day.saturday? || day.sunday?
          data["holidays"] << day.iso8601 if off.include?(day) && !weekend
          data["workdays"] << day.iso8601 if weekend && !off.include?(day)
        end
        puts "#{country} #{year}: ok"
      end
      File.write(Rails.root.join("config/calendars/#{country.downcase}.yml"),
                 "# Generated by `rake potee:calendars` from xmlcalendar.ru\n" + data.to_yaml)
    end
  end
end
