#!/usr/bin/env ruby
require File.expand_path('../../config/foreverb', __FILE__)

Forever.run :fork=>true do
  extend ForeverbConfig
  init_foreverb_config 'foreverb-cron'

  before :each do
    Rake::Task['environment'].invoke
  end

  every 1.day, :at => '2:35' do
    User.destroy_orphans
  end
end
